import "../styles/globals.css"
import type { Metadata } from "next"
import { poppins400 } from "../styles/fonts"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={poppins400.variable}>{children}</body>
    </html>
  )
}
